{"uuid": "ab66a7e8-e84d-411a-97c7-4f424af029df", "children": ["5d220b55-fd7a-4f55-8b0f-fd705c4cacf2"], "befores": [{"name": "start_exec", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'UserData.json'\n", "trace": "  File \"C:\\Users\\Katerina\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Katerina\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Katerina\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"e:\\Automation\\Pytest-API\\TestCases\\test_CreateUser.py\", line 12, in start_exec\n    file = open('UserData.json', 'r')\n"}, "start": 1652782946473, "stop": 1652782946473}], "start": 1652782946473, "stop": 1652782946479}