{"name": "test_Create_Other_User", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'UserData.json'", "trace": "scope = 'module'\n\n    @pytest.fixture\n    def start_exec(scope=\"module\"):\n        global file # it will make file global - used everywhere\n>       file = open('UserData.json', 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: 'UserData.json'\n\nTestCases\\test_CreateUser.py:12: FileNotFoundError"}, "start": 1652782946481, "stop": 1652782946481, "uuid": "3198b37d-1890-46de-8cbf-a4cef6d1f5cf", "historyId": "3b1fda0f7b6596a3ffc11be9708b1997", "testCaseId": "96e652b658cb77d99668f114276383fe", "fullName": "TestCases.test_CreateUser#test_Create_Other_User", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_CreateUser"}, {"name": "host", "value": "DESKTOP-DNTITBP"}, {"name": "thread", "value": "18392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_CreateUser"}]}